import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    """Update model field defaults and help_text to align with the Ophix theme palette."""

    dependencies = [
        ("admin_interface", "0004_theme_message_banner_text_colors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="theme",
            name="name",
            field=models.CharField(
                default="",
                max_length=50,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="title_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#fffdfa",
                help_text="Colour of the title text in the header bar",
                image_field=None,
                max_length=10,
                samples=None,
                verbose_name="color",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="css_header_background_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#0c0c0d",
                help_text="Background colour of the top header bar",
                image_field=None,
                max_length=10,
                samples=None,
                verbose_name="background color",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="css_header_text_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#fffdfa",
                help_text="Colour of plain text in the header bar",
                image_field=None,
                max_length=10,
                samples=None,
                verbose_name="text color",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="css_header_link_hover_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#ade9f4",
                help_text="Header link colour on hover",
                image_field=None,
                max_length=10,
                samples=None,
                verbose_name="link hover color",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="css_module_background_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#0c0c0d",
                help_text="Background colour of section header bars (module titles)",
                image_field=None,
                max_length=10,
                samples=None,
                verbose_name="background color",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="css_module_background_selected_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#f1fcfe",
                help_text="Background colour of selected / highlighted rows",
                image_field=None,
                max_length=10,
                samples=None,
                verbose_name="background selected color",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="css_module_link_hover_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#ade9f4",
                help_text="Link colour on hover inside section header bars",
                image_field=None,
                max_length=10,
                samples=None,
                verbose_name="link hover color",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="css_module_border_radius",
            field=models.CharField(
                blank=True,
                default="0",
                help_text="e.g. 4px · 0px · 0.5rem",
                max_length=20,
                verbose_name="border radius",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="css_generic_link_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#0096c7",
                help_text="Default link colour in page content",
                image_field=None,
                max_length=10,
                samples=None,
                verbose_name="link color",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="css_generic_link_hover_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#023e8a",
                help_text="Page content link colour on hover",
                image_field=None,
                max_length=10,
                samples=None,
                verbose_name="link hover color",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="css_generic_link_active_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#48cae4",
                help_text="Page content link colour when active / pressed",
                image_field=None,
                max_length=10,
                samples=None,
                verbose_name="link active color",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="css_save_button_background_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#0096c7",
                help_text="Background colour of Save / primary action buttons",
                image_field=None,
                max_length=10,
                samples=None,
                verbose_name="background color",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="css_save_button_background_hover_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#023e8a",
                help_text="Save button background colour on hover",
                image_field=None,
                max_length=10,
                samples=None,
                verbose_name="background hover color",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="css_button_border_radius",
            field=models.CharField(
                blank=True,
                default="0.3rem",
                help_text="e.g. 4px · 50% · Leave blank for no rounding.",
                max_length=20,
                verbose_name="border radius",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="css_delete_button_background_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#d81a00",
                help_text="Background colour of Delete / danger buttons",
                image_field=None,
                max_length=10,
                samples=None,
                verbose_name="background color",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="css_delete_button_background_hover_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#a31500",
                help_text="Delete button background colour on hover",
                image_field=None,
                max_length=10,
                samples=None,
                verbose_name="background hover color",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="css_warning_color",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#ddab52",
                help_text="#ddab52 — used for paused items, warnings, and amber UI states",
                image_field=None,
                max_length=10,
                samples=None,
                verbose_name="warning / paused color",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="css_message_success_bg",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#dff2e3",
                help_text="Background colour of success (green) system message banners",
                image_field=None,
                max_length=10,
                samples=None,
                verbose_name="success background",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="css_message_success_text",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#1a5c2b",
                help_text="Text colour of success (green) system message banners",
                image_field=None,
                max_length=10,
                samples=None,
                verbose_name="success text",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="css_message_warning_bg",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#faf3e5",
                help_text="Background colour of warning (amber) system message banners",
                image_field=None,
                max_length=10,
                samples=None,
                verbose_name="warning background",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="css_message_warning_text",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#7a5000",
                help_text="Text colour of warning (amber) system message banners",
                image_field=None,
                max_length=10,
                samples=None,
                verbose_name="warning text",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="css_message_error_bg",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#f5dede",
                help_text="Background colour of error (red) system message banners",
                image_field=None,
                max_length=10,
                samples=None,
                verbose_name="error background",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="css_message_error_text",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#6b0f0f",
                help_text="Text colour of error (red) system message banners",
                image_field=None,
                max_length=10,
                samples=None,
                verbose_name="error text",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="css_message_info_bg",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#d9f0f7",
                help_text="Background colour of info (cyan) system message banners",
                image_field=None,
                max_length=10,
                samples=None,
                verbose_name="info background",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="css_message_info_text",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#004d66",
                help_text="Text colour of info (cyan) system message banners",
                image_field=None,
                max_length=10,
                samples=None,
                verbose_name="info text",
            ),
        ),
    ]
